version: 4.0.1-{build}
skip_tags: true

environment:
  github_apikey:
    secure: scoX9iR0iwbkHsEc7X0doOONik+WW93s4adA4T3Zcbr2MrsEK6LWnMLfdSctATjx
  nuget_apikey:
    secure: i/4GCUy+iqG/ytoKAFwTXJqOjSNqnzo8gJmLiiB0dWjVG6j//71LC01FWWig5B9d
  docker_password:
    secure: 3BLFSWasBkoBDnePlBhgN0zzV0lRnmJ+BJ2WFEKHIKMt1f0j/CimHAZKFSzu9jvA
  octopus_apikey:
    secure: XUJisBpllF5tywdA3kclw3hbZqJ/MTnf90j6kTVxe8M=

services:
  - docker

install:
  #- git clone -b develop --single-branch https://$github_apikey@github.com/280CapMarkets/TwoEightyCap.DevOps.Tools.git ~\tools
  #- .\~\tools\dist\tools/Init.ps1
  
build_script:
    - ps: dotnet build /p:Version=$env:APPVEYOR_BUILD_VERSION /p:Configuration=Release
test_script: 
    #- ps: dotnet test --filter 
after_test: 
    - ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION /p:Configuration=Release -o ../../artifacts
    - ps: dotnet nuget push artifacts\*.nupkg -k $env:nuget_apikey -s https://www.myget.org/F/280capmarkets/auth/$env:nuget_apikey/api/v3/index.json

artifacts:
  - path: 'src\**\*.nupkg'
    name: nuget-package
    
cache:
  - $HOME/.nuget/packages -> **\*.csproj
  - $HOME/.dotnet/tools -> **\*.csproj
  - packages -> **\*.csproj

matrix:
  fast_finish: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
